export const CATEGORIES = {
  animations: "animations",
  shadows: "shadows",
  gradients: "gradients",
  images: "images",
  color: "color",
  shapes: "shapes",
  typography: "typography",
  a11y: "a11y",
  other: "other",
  layout: "layout",
};

export const generators = [
  {
    url: "https://9elements.github.io/fancy-border-radius/",
    categories: [CATEGORIES.other],
  },
  { url: "https://shadows.brumm.af/", categories: [CATEGORIES.shadows] },
  {
    url: "https://cubic-bezier.com/#.17,.67,.83,.67",
    categories: [CATEGORIES.animations],
  },
  {
    url: "https://larsenwork.com/easing-gradients/",
    categories: [CATEGORIES.gradients],
  },
  {
    url: "https://omatsuri.app/triangle-generator/",
    categories: [CATEGORIES.shapes],
  },
  {
    url: "https://omatsuri.app/color-shades-generator",
    categories: [CATEGORIES.color],
  },
  {
    url: "https://omatsuri.app/gradient-generator",
    categories: [CATEGORIES.gradients],
  },
  { url: "https://omatsuri.app/page-dividers", categories: [CATEGORIES.other] },
  { url: "https://svg-css.dotenv.dev/", categories: [CATEGORIES.images] },
  {
    url: "https://mybrandnewlogo.com/color-gradient-generator",
    categories: [CATEGORIES.gradients],
  },
  { url: "https://typescale.com/", categories: [CATEGORIES.typography] },
  {
    url: "https://www.thegoodlineheight.com/",
    categories: [CATEGORIES.typography],
  },
  { url: "https://bennettfeely.com/clippy/", categories: [CATEGORIES.shapes] },
  { url: "https://griddy.io/", categories: [CATEGORIES.layout] },
  {
    url: "https://codepen.io/michellebarker/full/zYOMYWv",
    categories: [CATEGORIES.layout],
  },
  {
    url: "https://codepen.io/stoumann/full/MWeNmyb",
    categories: [CATEGORIES.other],
  },
  { url: "https://www.imagemaps.net/", categories: [CATEGORIES.images] },
  { url: "https://animista.net/", categories: [CATEGORIES.animations] },
  {
    url: "https://codepen.io/jh3y/full/MWJdqBo",
    categories: [CATEGORIES.shapes],
  },
  { url: "https://accessiblepalette.com/", categories: [CATEGORIES.a11y] },
  {
    url: "https://animated-gradient-background-generator.netlify.app/",
    categories: [CATEGORIES.gradients],
  },
  { url: "https://pr.gg/base64/", categories: [CATEGORIES.images] },
  {
    url: "https://maxbittker.github.io/broider",
    categories: [CATEGORIES.other],
  },
  {
    url: "https://getcssscan.com/css-buttons-examples",
    categories: [CATEGORIES.layout],
  },
  {
    url: "https://getcssscan.com/css-box-shadow-examples",
    categories: [CATEGORIES.shadows],
  },
  { url: "https://easings.co/", categories: [CATEGORIES.animations] },
  { url: "https://easings.net/", categories: [CATEGORIES.animations] },
  {
    url: "https://easyeasings.com/",
    categories: [CATEGORIES.animations],
  },
  { url: "https://keyframes.app/animate", categories: [CATEGORIES.animations] },
  {
    url: "https://svgartista.net/",
    categories: [CATEGORIES.animations],
  },
  {
    url: "https://www.transition.style/",
    categories: [CATEGORIES.animations],
  },
  { url: "https://alphredo.app/", categories: [CATEGORIES.color] },
  { url: "https://buttonbuddy.dev/", categories: [CATEGORIES.a11y] },
  { url: "https://hypercolor.dev/", categories: [CATEGORIES.gradients] },
  { url: "https://hypercolor.dev/flags", categories: [CATEGORIES.color] },
  {
    url: "https://www.joshwcomeau.com/gradient-generator/",
    categories: [CATEGORIES.gradients],
  },
  {
    url: "https://meshgradient.in/",
    categories: [CATEGORIES.gradients],
  },
  { url: "https://easycolour.app/", categories: [CATEGORIES.color] },
  { url: "https://copypalette.app/", categories: [CATEGORIES.color] },
  {
    url: "https://www.conic.style/",
    categories: [CATEGORIES.gradients],
  },
  {
    url: "https://uigradients.com/",
    categories: [CATEGORIES.gradients],
  },
  {
    url: "https://cssarrowplease.com/",
    categories: [CATEGORIES.shapes],
  },
  {
    url: "https://www.khroma.co/generator",
    categories: [CATEGORIES.color, CATEGORIES.layout],
  },
  {
    url: "https://www.magicpattern.design/tools/css-backgrounds",
    categories: [CATEGORIES.shapes],
  },
  { url: "https://layout.bradwoods.io/", categories: [CATEGORIES.layout] },
  {
    url: "https://www.magicpattern.design/tools/confetti-generator",
    categories: [CATEGORIES.shapes],
  },
  {
    url: "https://www.magicpattern.design/tools/add-grain-to-images",
    categories: [CATEGORIES.images],
  },
  {
    url: "https://www.magicpattern.design/tools/wave-generator",
    categories: [CATEGORIES.shapes],
  },
  {
    url: "https://www.magicpattern.design/tools/blob-generator",
    categories: [CATEGORIES.shapes],
  },
  {
    url: "https://alvarotrigo.com/shadow-gradients/",
    categories: [CATEGORIES.shadows],
  },
  {
    url: "https://stripesgenerator.com/",
    categories: [CATEGORIES.shapes],
  },
  {
    url: "https://www.shapedivider.app/",
    categories: [CATEGORIES.shapes],
  },
  {
    url: "https://doodad.dev/pattern-generator/",
    categories: [CATEGORIES.shapes],
  },
  {
    url: "https://www.fluid-type-scale.com/",
    categories: [CATEGORIES.typography],
  },
  {
    url: "https://meowni.ca/font-style-matcher/",
    categories: [CATEGORIES.typography],
  },
  { url: "https://ui.glass/generator/", categories: [CATEGORIES.layout] },
  {
    url: "https://www.joshwcomeau.com/shadow-palette/",
    categories: [CATEGORIES.shadows],
  },
  {
    url: "https://www.cssgradienttext.com/",
    categories: [CATEGORIES.typography, CATEGORIES.gradients],
  },
  {
    url: "https://mdbootstrap.com/docs/standard/tools/design/instagram-filters/#generator",
    categories: [CATEGORIES.images],
  },
  {
    url: "https://csshero.org/mesher/",
    categories: [CATEGORIES.gradients],
  },
  {
    url: "https://modern-fluid-typography.vercel.app/",
    categories: [CATEGORIES.typography],
  },
  { url: "https://pixelcorners.lukeb.co.uk/", categories: [CATEGORIES.shapes] },
  {
    url: "https://screenspan.net/polka/",
    categories: [CATEGORIES.shapes],
  },
  { url: "https://ratiobuddy.com/", categories: [CATEGORIES.other] },
  {
    url: "https://range-input-css.netlify.app/",
    categories: [CATEGORIES.layout],
  },
  { url: "https://neumorphism.io/#e0e0e0", categories: [CATEGORIES.layout] },
  {
    url: "https://transparenttextures.com/",
    categories: [CATEGORIES.shapes],
  },
  {
    url: "https://typescale.com/",
    categories: [CATEGORIES.typography],
  },
  {
    url: "https://www.vanillabreeze.dev/",
    categories: [CATEGORIES.other],
  },
  { url: "https://favicon.io/", categories: [CATEGORIES.images] },
  { url: "https://icon.kitchen/", categories: [CATEGORIES.images] },
  {
    url: "https://brandmark.io/logo-crunch/",
    categories: [CATEGORIES.images],
  },
  {
    url: "https://toolcool.org/random-favicon-generator",
    categories: [CATEGORIES.images],
  },
  {
    url: "https://formito.com/tools/favicon",
    categories: [CATEGORIES.images],
  },
  { url: "https://prism.dotenv.dev/", categories: [CATEGORIES.other] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
  { url: "", categories: [""] },
].filter((a) => a.url);
